### ISSUE TITLE
License

### ISSUE THREAD

**Issue by agnor99** [hjake123/reactive#1]
Hey, your mod looks cool, but I wanted to tell you, that the GPL 3.0 is not a valid license for minecraft mods.
A short explanation can be found [in this modrinth blog post](https://blog.modrinth.com/p/licensing-guide).
You might want to consider to change it.

**Comment by hjake123** [comment]
Thank you for bringing this to my attention

**Comment by hjake123** [comment]
For the record, the mod is under the CC BY-NC 4.0 license. That license matches my intent anyway so thank you again for pointing out the issur.
