### ISSUE TITLE
Made acid in Universio modpack but smooth stone just says connecting

### ISSUE THREAD

**Issue by cinimodphoto** [hjake123/reactive#10]
After creating acid using gunpowder, spider eyes and crimson stuff, I dropped the smooth stone in and it just says Connecting when I mouse over it. I tried 1 gunpowder all the way to a full stack making the water turn red and still nothing.
![Crucible Connecting](https://user-images.githubusercontent.com/58937962/236836418-8afac5f5-9a5e-4aba-a021-4ae03edf1df5.png)

**Comment by cinimodphoto** [comment]
Nevermind, appears in my testing I grabbed the wrong smooth stone. It works just fine.

**Comment by Chromium2312** [comment]
how do you make acid the book isnt very clear on it

**Comment by hjake123** [comment]
Acid can be made using any of the items in the `#reactive:acid_sources` tag. You can search for the tag in JEI or use the client-side config option to see which items,

Once you find the item, drop enough in that the water changes color and then add the ingredient you want to change. The amount of items you need to use (the 'strength' of the acid) may vary depending on the recipe you're trying to do.
