### ISSUE TITLE
[New Feature/Enhancement] Recipes transmutation item-tag support

### ISSUE THREAD

**Issue by DevDyna** [hjake123/reactive#13]
(i don't think that need other desc except the title)
Example with #forge:flowers->deepslate with reagent "mind" 
`{
            "type": "reactive:transmutation",
            "reactant": {
                "tag": "#forge:flowers"
            },
            "product": {
                "item": "minecraft:deepslate"
            },
            "reagents": ["reactive:mind"],
            "min": 10,
            "cost": 10
        }`

**Comment by hjake123** [comment]
I'll plan to add this for the next release

**Comment by hjake123** [comment]
Added for release in version 1.19.2-5
