### ISSUE TITLE
Triggering a Gold Foam reaction crashes the game

### ISSUE THREAD

**Issue by 301Gabe** [hjake123/reactive#14]
Whenever I trigger a gold foam reaction, the game crashes. When I log back in, the reaction has finished.

**Comment by 301Gabe** [comment]
[crash-2023-07-14_18.54.33-client.txt](https://github.com/hjake123/reactive/files/12059507/crash-2023-07-14_18.54.33-client.txt)

**Comment by hjake123** [comment]
Very strange. Is there any gold foam produced by this?

**Comment by 301Gabe** [comment]
Yes.

**Comment by hjake123** [comment]
Thanks for the report! I'll look into it. The crash itself is easy to fix but I'm not yet sure why it happened

**Comment by hjake123** [comment]
Either way, it'll be fixed for the next release

**Comment by hjake123** [comment]
Resolved in 5c
