### ISSUE TITLE
Suggestion: Creative "View All" cheat

### ISSUE THREAD

**Issue by CTH999** [hjake123/reactive#18]
So, this idea is simple. It's the ability to, using a creative command, completly fill the book, so you know all the recipes. For those willing to have spoilers, and learn the more intriciase of mechanics, not discovering (So, someone could find how to optimize ratios, and bypass finding every recipe first)

**Comment by hjake123** [comment]
This is already possible! One way to do this is to grant yourself the relevant advancements. If you use the `/advancement grant @p only reactive:(advancement_name)` command to give yourself one of the reactive advancements, the corresponding book entries will unlock.

If you'd prefer to disable the advancement gating entirely, go to `config/patchouli-client.toml` and add `reactive:journal` to the `noAdvancementBooks` list. This will reveal all entries.

You might also be interested in the client config option that shows all Power sources, located in `configs/reactive-client.toml`

**Comment by CTH999** [comment]
okay. Thing is, I used /advancement grant @p all...

**Comment by hjake123** [comment]
That would also work but it would mess with other mods and the vanilla advancement track... All the pages should be unlocked in that case though
