### ISSUE TITLE
Is there a way to customize reagents names located in jei ?

### ISSUE THREAD

**Issue by Thirace446** [hjake123/reactive#20]
Renaming items is no problem 
![20230923215358](https://github.com/hjake123/reactive/assets/55902963/0c76fd7a-a5f6-46d3-908d-d765ba987b6a)
but
![20230923215357](https://github.com/hjake123/reactive/assets/55902963/ec51852c-a01d-4b5f-9bb7-2a57d2030397)

What is the correct key value?

**Comment by hjake123** [comment]
At the moment, there is not, but I'm pretty surprised about that so give me a moment to add a key that controls those names.

**Comment by hjake123** [comment]
This will be fixed in the next update. Thanks for bringing it to my attention! If you finish that translation feel free to make a PR!

**Comment by hjake123** [comment]
Did you continue this translation project? I would love to incorporate it into the base mod if you did!
