### ISSUE TITLE
[1.20.1] Server No Start

### ISSUE THREAD

**Issue by HockeyZman2000** [hjake123/reactive#21]
[latest.log](https://github.com/hjake123/reactive/files/12773939/latest.log)

No references to any outside mods that I can see
Forge 47.1.47
Reactive 1.20.1-6a

**Comment by Nostalgion** [comment]
i'm having this same issue, works fine in sp, but on a dedicated server it tries to load as client and fails to boot

**Comment by hjake123** [comment]
Ah damn okay, sorry about that. Should be an easy enough fix

**Comment by hjake123** [comment]
I believe 1.20.1-6b resolves this. (I was able to load onto a dedicated server with Create)

**Comment by hjake123** [comment]
Alright, hopefully everything is resolved here.
