### ISSUE TITLE
[Bug] Reactive sources on JEI Bookmarks send on crash client

### ISSUE THREAD

**Issue by DevDyna** [hjake123/reactive#27]
`[i can't provide a crashlog client but can be easly replicable]`

How to reproduce : 
- Open a world with reactive and jei installed
- find a recipe with any source used on jei
- press "A" (or the bookmark key used to save) on top of the source of recipe like `reactive:soul`
- look on bookmarks by move the cursor over the source saved
- the game crash

tested on [1.19.2 modded](https://github.com/DevDyna/IronBerry)

also on bookmark.ini from jei the element still saved as `O:soul`

**Comment by hjake123** [comment]
Ah! Interesting, thanks for the report.

**Comment by hjake123** [comment]
Fixed in 1.19.2-7b and 1.20.1-7d
