### ISSUE TITLE
[New Feature/Enhancement] Litmus paper colored output

### ISSUE THREAD

**Issue by DevDyna** [hjake123/reactive#29]
I' just wondering why not change chat color for all *power/sources* displayed when used a Litmus paper ?
It will help players with multiple crucibles and need to identify a specific *power/source* 
(using same color of bottles)

example:
(color format add a custom font , it isnt intended)

${{\color{gray}\Huge{\textsf{  --\ Measurement\ --\ \}}}}\$
${{\color{purple}{\textsf{  ACID-CAUSTIC\ \ \}}}}\$ - 12%
${{\color{orange}{\textsf{  FIRE-BLAZE\ \ \}}}}\$ - 63%
${{\color{magenta}{\textsf{  MAGIC-MIND\ \ \}}}}\$ - 26%
${{\color{lightblue}{\textsf{  SOUL\ \ \}}}}\$ - 53%
${{\color{cyan}{\textsf{  WARP\ \ \}}}}\$ - 11%
${{\color{green}{\textsf{  VERDANT-NATURE\ \ \}}}}\$ - 58%
${{\color{brown}{\textsf{  BODY-STOCK\ \ \}}}}\$ - 36%
${{\color{yellow}{\textsf{  LIGHT\ \ \}}}}\$ - 48%
${{\color{red}{\textsf{  LIFE-VITAL\ \ \}}}}\$ - 99%

**Comment by hjake123** [comment]
That's an interesting idea! I wonder if the chat output supports hex color codes- if so I can literally have it apply the Power color from each one's registry entry

**Comment by hjake123** [comment]
(By the way, thank you for the consistent reports!)

**Comment by hjake123** [comment]
To be added in the imminent 1.20.1-8 release
