### ISSUE TITLE
Crash upon water touching copper symbols

### ISSUE THREAD

**Issue by MindFaer** [hjake123/reactive#3]
[crash-2023-01-24_03.59.11-server.txt](https://github.com/hjake123/reactive/files/10487884/crash-2023-01-24_03.59.11-server.txt)
Attached is the crash log from this instance

To recreate: place water above a copper symbol and let it flow down onto it, doing so crashes the game after a long pause

Edit: tested this with all other symbols and they provide the same crash message, albiet from a different block in the logs, attached is the occult one just in case this one is different
[crash-2023-01-24_04.11.52-client.txt](https://github.com/hjake123/reactive/files/10487954/crash-2023-01-24_04.11.52-client.txt)

**Comment by hjake123** [comment]
Oh! Good catch, thanks

**Comment by hjake123** [comment]
It's a crashing bug so I'll release a new version whenever curseforge servers stop dying
