### ISSUE TITLE
Enhanced functionality with Valkyrien Skies

### ISSUE THREAD

**Issue by Tysos24** [hjake123/reactive#33]
I’ve yet to actually play the mod; the only bit of it I’ve seen is [this video](https://www.reddit.com/r/feedthebeast/comments/10iufti/my_first_big_mod_reactive_alchemy_sample_video/), but if that reaction gave the blocks it affected actual physics when VS was installed it would be cool. And there are probably other things like it that would work too.

**Comment by hjake123** [comment]
Interesting idea! I might look into that sometime if the VS API is easy to use
