### ISSUE TITLE
Possibly give a bit more info in Peculiar Circumstance?..

### ISSUE THREAD

**Issue by slava110** [hjake123/reactive#37]
Most of the time it's not that hard to progress further in the mod. However, it wasn't the case for me with Peculiar Circumstance. Book says to combine Mind, Body, and some other ingredient. I thought it needs item ingredient but it was a power (in fact, 2 different can be used for different effects). Maybe it is possible to vaguely reflect that it's a specific power?.. And that there's 2 of them. Maybe it's just me though and it's kinda obvious to get that

**Comment by hjake123** [comment]
I never thought of it that way! Thanks for the feedback, I can definitely clarify the wording there.

**Comment by hjake123** [comment]
The fact that there's two of them is intentionally secret until the second step of that research line though
