### ISSUE TITLE
Reduction/Enlargement size control

### ISSUE THREAD

**Issue by slava110** [hjake123/reactive#38]
Would be cool to be able to control target size for Reduction and Enlargement. Maybe it could be controlled by amount of power in the cauldron? Or something else?
If it's hard to implement, target size could be added to config file at least c:

**Comment by hjake123** [comment]
Personally I feel that the more extreme Pehkui sizes are a little OP, but I can definitely put the 'small' and 'large' scale values in a config somewhere.

**Comment by slava110** [comment]
Cool!
It's useful because in my modpack you can pick up villagers using Easy Villagers mod and use them in autotraders but only if they're small enough to fit in your hand (>0.25 base size). Maybe there could be other uses for size changing too c;

**Comment by hjake123** [comment]
The size changing power config has been added 1.20.1-8b.
