### ISSUE TITLE
"Mechanical hands" aren't Create mechanical hands :0

### ISSUE THREAD

**Issue by slava110** [hjake123/reactive#40]
In Ender Pearls entry (objects to study) book mentions mechanical hands. I thought it's some kind of Create integration and tried mechanical hands from Create xD Didn't work. Then I thought it could be some kind of mod item/block, but after progressing through the mod, I haven't found anything like that. Wasn't obvious for me that "mechanical hand" could be a dropper. Maybe it's just me or it could be described a bit better

**Comment by hjake123** [comment]
Ah yeah I wasn't even considering Create when adding that entry... Technically the pearl just has to be added by anything other then a player throwing it in. Will clarify.

**Comment by slava110** [comment]
Maaybe some players might think about throwing pearl with right click (because that's how it remembers player in vanilla)? And they might try to throw it using dispenser or something xD

**Comment by hjake123** [comment]
I think dispensers still work, if the pearl actually lands inside, so this wouldn't be a terrible belief on the player's part. Another player might try using a hopper (which works) or some other mod's downward dropping device.

**Comment by slava110** [comment]
DAMN, HOPPER WORKS?!
You should've seen how much time I've spent on getting this pearl inside using dropper xD
Because it's dropping with random offset, it's really hard to put stuff into cauldron using dropper

**Comment by hjake123** [comment]
Clarified in 1.20.1-8c
