### ISSUE TITLE
Add some kind of "unfinished" marker in Patchouli book?

### ISSUE THREAD

**Issue by slava110** [hjake123/reactive#41]
When you progress through the mod, you can forget what you've already tried and what you haven't. For example, I forgot that I didn't try "mechanical hands" behaviour with ender pearls after progressing through the mod.
There are "unfinished" markers for some entries already but not all of them.
Would be handy to have these unfinished markers in `Objects to study` chapters until you really studied everything you can about specific object.
![2024-04-23_09 50 45](https://github.com/hjake123/reactive/assets/26705162/82630a68-38a1-4476-bd95-2ac070b36e77)

**Comment by hjake123** [comment]
After going back and forth on this for a while, I think this would be a good change. Implemented for 1.20.1-8c.
