### ISSUE TITLE
Hostile mobs should avoid luminous ring like they avoid sunlight

### ISSUE THREAD

**Issue by slava110** [hjake123/reactive#43]
When sun arises, some mobs (skeletons for sure, maybe zombies too) hide under trees, inside water to not burn under the sun. In other words, they actively avoid sunlight. Do you think they should avoid luminous ring in a similar way? (unless player has been spotted)

**Comment by hjake123** [comment]
I didn't know they had that ability to be honest

**Comment by hjake123** [comment]
It seems that that vanilla system is hardcoded to only work with light levels. It might be possible with mixin but I think I'll leave this for now.

**Comment by slava110** [comment]
Sure. AI is one of the hardest things in minecraft. And this technically doesn't affect gameplay that much.
You can even say that hostile mobs don't see this luminous ring. And when they enter they don't know what's happening (because it's not a natural thing like normal sunlight)

**Comment by hjake123** [comment]
I think I'm going to finally decide not to add this. Maybe someday, but I want to close the issue.
