### ISSUE TITLE
Use gold symbol to infuse sculk catalyst with Life?

### ISSUE THREAD

**Issue by slava110** [hjake123/reactive#44]
After reading "Something that spreads" entry, I've tried to use gold symbol to pass life to sculk catalyst instead of just throwing it into cauldron xD
Life currently doesn't have any effect with gold symbol AFAIK. Maybe it could activate sculk catalyst spread when it's nearby?

**Comment by hjake123** [comment]
Eh, I don't really want to make the Crucible check for nearby Sculk Catalysts every half second that it's got Gold Symbol + Vital
