### ISSUE TITLE
Broken reagent display in Patchouli book

### ISSUE THREAD

**Issue by slava110** [hjake123/reactive#45]
![2024-04-23_10 29 29](https://github.com/hjake123/reactive/assets/26705162/20662426-e2bd-43e3-8bf4-eae8e72f38d6)
![2024-04-23_10 31 43](https://github.com/hjake123/reactive/assets/26705162/7df93fb0-09af-4e59-a802-eab396dcfe89)

**Comment by hjake123** [comment]
Huh.

**Comment by hjake123** [comment]
This was present since 1.20.1-8a apparently?? Yikes!

**Comment by hjake123** [comment]
To be fixed in 1.20.1-8c. If you're desperate for it to be fixed earlier, I've hotfixed on Modrinth so that that version of 8b has the fix as well.

**Comment by slava110** [comment]
Yeah, I've been playing with this bug present actually. But had so much fun so it wasn't really an issue for me. You can still see powers if you look closely xD
