### ISSUE TITLE
Useful mind book writing

### ISSUE THREAD

**Issue by slava110** [hjake123/reactive#47]
About writable book in the cauldron.
Random idea: what if, under certain circumstances, instead of writing gibberish it would write some creepy stuff (like `I see you, $playername` / `Behind you`) or give useful info? Or give enchanting books / pieces of lore / patchouli book pages / recipe pages / tips or hints

**Comment by hjake123** [comment]
Try doing with books that have multiple pages of only whitespace

**Comment by slava110** [comment]
So like... Already implemented? :0

**Comment by hjake123** [comment]
Yep! By the way, thanks for all the feedback! It's good to know what parts of the mod are still rough around the edges.

**Comment by slava110** [comment]
Thanks for one of the best mods for minecraft IMO :p
Last time I've been so invested in mod mechanics and secrets was Hex Casting mod by Petrak (it also had a bit of lore, secrets. And a lot of programming xD).
Literally played for hours with your mod and had so much fun with it.
I really like how you initially don't know anything and then learn different mechanics, applications of powers, combinations, etc. .
I also liked 2 little diagrams in the mod. Mysterious and yet simple to understand once you read what it is all about. Would be cool to see more in the future!
I was afraid initially that I will need to blindly experiment with a bunch of stuff, but with `Objects to study` and `Reactions` tabs it's really easy and fun to progress in the mod and learn new stuff :p
The only thing I'm currently worried about is how hard will it be for me to integrate it in my modpack. But we'll see.
I saw your mod in UniversIO modpack initially but not even a fraction of what is possible in your mod has been used in that pack. Just a few transformation recipes :c

**Comment by hjake123** [comment]
Thanks! I've been on break with developing this for a few weeks since I've had stuff to work on elsewhere but it's nice to get back into it so to speak.
