### ISSUE TITLE
Cauldron percentage is "floored"

### ISSUE THREAD

**Issue by slava110** [hjake123/reactive#48]
Because you're dividing int by int, you're ignoring fractional part of percentage.
https://github.com/hjake123/reactive/blob/289c31e9907dd6ed3efc390b4d448bfaf2649a25/src/main/java/com/hyperlynx/reactive/items/LitmusPaperItem.java#L146
This results in cauldron never being full on paper (and on Create display link).
![2024-04-23_12 14 36](https://github.com/hjake123/reactive/assets/26705162/af48b830-af94-423a-8ed3-42dbf9b5d5f8)
Maybe you can use double and round it to closest number instead (and maybe leave 1 character after the dot. I mean, format it like `50.4%`, `49.6%` instead of just `50%`, `50%`. A bit more precise. But up to you. Keep in mind that changing NBT value type might lead to crash on client side).

**Comment by hjake123** [comment]
The imprecision is intended, but I could have sworn it was possible for the paper to report 100% values... Either way a little rounding might be nice

**Comment by slava110** [comment]
Possible with single power inside :shrug:

**Comment by hjake123** [comment]
I might do this later, but for now I don't plan to change this. I don't want everyone to get confused when their percents change by a tiny amount.
