### ISSUE TITLE
Method to hide the Framed Motion Salt Block path in a Displacement build

### ISSUE THREAD

**Issue by slava110** [hjake123/reactive#49]
Might be useful to combine displace with warp/teleportation cloud thingy or something else to:
- Teleport block from one place to another
- Swap blocks between 2 positions
- Swap block in one position (for example, put another block when block is dispaced, and toggle displacement to change it to original one and vice-versa)
I'm not sure if it wouls fit mod lore, I'll check at home. Just random ideas :p
Also it would be easier to use displace in builds if there would be some way to hide salt "path" from redstone to blocks you want to displace.

**Comment by hjake123** [comment]
The teleporting block mechanics are not ones I'm super interested in but yeah I've been considering for a while about ways to hide the FMSB line in displace builds. 

Maybe Copper could 'conduct' the displace effect without actually displacing, so it could be an opaque stand in for FSMBs in a chain displace

**Comment by hjake123** [comment]
To be added in 1.20.1-8c
