### ISSUE TITLE
Make unformed matter passable/unbreakable for easier automation

### ISSUE THREAD

**Issue by slava110** [hjake123/reactive#51]
Hi. Made simple concept for ore automation using Create mod. The problem with unformed matter here is that you cannot detect when all blocks have been transformed into ore. Technically you can, but... You need a lot of observers and then somehow combine all signals in one big AND gate. And you can break unformed matter using Create drills and you'll lose ore block :c
Techincally this could be avoided by making unformed matter passable for drills if it's possible and it will work (like it works with crop blocks in Create mod). Or maybe unbreakable in general. What do you think?
![2024-04-24_10 00 12](https://github.com/hjake123/reactive/assets/26705162/11f25a3d-ba49-4f58-a303-5f973498c493)

**Comment by hjake123** [comment]
This is an intentional automation challenge. A survival player will likely not be able to maintain a whole huge row of Astral crucibles like this.
