### ISSUE TITLE
Particles are buffered while game is paused

### ISSUE THREAD

**Issue by slava110** [hjake123/reactive#52]
When you look at a crucible with astral power, then pause your game for a few seconds, and unpause - you can see a lot of particle spawning. Maybe this is caused by particle spawning being dependent on system time or some kind of external timer instead of in-game client ticks. In theory could cause lag when you return to the game after long period of time, but not sure about that.
A bit strange to see that anyway
![2024-04-24_10 07 03](https://github.com/hjake123/reactive/assets/26705162/685c2b50-73f8-4003-b6c7-b44817c99608)
![2024-04-24_10 07 12](https://github.com/hjake123/reactive/assets/26705162/be646967-0a21-4730-8399-c0b7d3e32ab4)
![2024-04-24_10 07 19](https://github.com/hjake123/reactive/assets/26705162/6be0ab17-b198-47ef-a209-e591f7546d02)

**Comment by hjake123** [comment]
This is an issue that's been there for a long time, I think it has to do with some particles originating on the logical server.

**Comment by hjake123** [comment]
Fix in the upcoming 1.21 port.
