### ISSUE TITLE
Mind lichen rework

### ISSUE THREAD

**Issue by slava110** [hjake123/reactive#54]
When you walk on mind lichen it extracts some xp from you into the world and grows. Because of that you can walk forward on it and it will spread below your legs unless you somehow lose this experience orb. And you can cover the whole world in it.
Btw, might be cool to grow it using xp orbs in the world (for example dropped from mobs or from ore). Or maybe make it grow passively. Would open second option for mind automation.
UPD: Oh, there's even no proper entry about mind lichen. Is it something that is WIP?

**Comment by hjake123** [comment]
It's covered in whatever entry is about uses of vines. I think it's a Results entry? 

The spread is intended behavior since you can just jump away from the lichen or break it to escape the situation

**Comment by hjake123** [comment]
Spreading on contact with xp could be good, but it would mean that if you step on the lichen, it grows, and then your orb hits it, your levels are gone.

**Comment by slava110** [comment]
Well, yeah. There's an entry about cultivation. From this entry I know that it exists and it should be studied further. I thought it would grow and give me mind (because I was in creative) but it didn't really grow. Only after reading code I understood that I need to be in survival to interact with it. Maybe it's easy to find out in survival mode though :shrug:
![2024-04-24_20 57 30](https://github.com/hjake123/reactive/assets/26705162/3f9c4c4f-bcd1-4e6b-bb32-aeb653744ad2)
Idk how I feel about this mechanic with spreading. Because...
From player's perspective it looks weird. You walk and xp orb is constantly on your legs bouncing. And lichen spreads when you walk just because xp orb is picked up instantly. Looks more like some kind of bug to me
From automation perspective it isn't useful too. You cannot use this mechanic without player. Technically you can bonemeal it but it will be costly to get a bit of Mind.

**Comment by hjake123** [comment]
Hmm. The lichen was definitely from a time where features were being added just because, without much gameplay consideration. I'll think about this, maybe a rework is in order sometime

**Comment by hjake123** [comment]
A change in how Mind Lichen work has been implemented for the upcoming 1.21-9 release (including a new thing for them to do).
