### ISSUE TITLE
[BUG 1.19.2] Tank duplication on filling Crucible

### ISSUE THREAD

**Issue by DevDyna** [hjake123/reactive#55]
https://github.com/DevDyna/IronBerry/issues/19

**Comment by hjake123** [comment]
Huh. Very strange, I'll look into this when I have time

**Comment by hjake123** [comment]
Issue will be fixed in next 1.19.2 release. Now to check if it affects 1.20.1...

**Comment by hjake123** [comment]
Fixed in 1.19.2-7e and 1.20.1-8d
