### ISSUE TITLE
[1.21.1 NeoForge] Crashing when reading Litmus Paper 

### ISSUE THREAD

**Issue by dainekoichi** [hjake123/reactive#58]
[crash-2024-09-30_16.30.42-server.txt](https://github.com/user-attachments/files/17186534/crash-2024-09-30_16.30.42-server.txt)

The crash happens in the dedicated server and the client just disconnects. This might possibly be due to Biomes O' Plenty?

**Comment by hjake123** [comment]
Ah, this looks like a 'dedicated server trying to access client classes' issue. Working on it now

**Comment by hjake123** [comment]
Fixed in `1.21.1-9b`
