### ISSUE TITLE
Crashing when performing Water Writing [1.21.1 NeoForge]

### ISSUE THREAD

**Issue by dainekoichi** [hjake123/reactive#59]
Dedicated Server Log: https://mclo.gs/NXDK5Ne
Singleplayer Log: https://mclo.gs/yq52L8N

Not sure if it's conflicting with other mods, but crash log is provided above
EDIT: It also happens in singleplayer after trying to reproduce. Added another log above

**Comment by dainekoichi** [comment]
For now I've installed Neruina to prevent the world/s from being unenterable.

**Comment by hjake123** [comment]
Ah man! Thanks for reporting, I'll get that patched and try to see if there's anything similar I missed elsewhere

**Comment by hjake123** [comment]
It looks like written book contents became immutable at some point, which is strange since I'm sure I tried water writing after the 1.20.6 port. Maybe they changed again...?

**Comment by hjake123** [comment]
Fixed in 1.21.1-9c
