### ISSUE TITLE
Resultant items from power release match input stack size even if not all items were consumed due to Power level cap. (1.21, Neoforge)

### ISSUE THREAD

**Issue by Aeonsteel** [hjake123/reactive#65]
Title. I also have Sinytra Connector installed if that matters.

For example, a full stack of Amethyst Shards will fill the crucible to 100% Mind with 24 shards leftover, but will still give 64 pure quartz and return the 24 amethyst.

**Comment by hjake123** [comment]
Fixed in 1.21.1-9g
