### ISSUE TITLE
Issue with recipe viewers when using both JEI and EMI

### ISSUE THREAD

**Issue by Aeonsteel** [hjake123/reactive#68]
Reactive's recipe types don't show on the latest version of Reactive and JEI when EMI is installed too. (1.21.1-9i)

![image](https://github.com/user-attachments/assets/86278f1d-5198-4aa6-8998-4f4e12ae1b9c)

The recipes still show up in 1.21.1-9h however.

**Comment by hjake123** [comment]
Huh. JEI's API itself has started to phase out the getBackground() method (and was giving me compiler warnings for implementing it) but it seems like maybe EMI requires it?

**Comment by hjake123** [comment]
Yep, that's the issue. Note to self to not refactor things without REALLY extensive testing...

Fixed in 1.21.1-9j

**Comment by Aeonsteel** [comment]
This can be safely reverted now, EMI has fixed the issue on their end as well.

**Comment by hjake123** [comment]
Ah, ok. I'll add it to the list. Thanks for letting me know!
