### ISSUE TITLE
More redstone integration.

### ISSUE THREAD

**Issue by arsserpentarium** [hjake123/reactive#7]
Hello. I would like to ask you to add more features, which allow automation of alchemical manipulations. What can I suggest?

Hopper integration.
1. Hopper above crucible should be able to input reagents for dissolution and transmutation.
It should work a lot like composter. So, when hopper is trying to put object into cradle, it should perform with said object all operations, which happens in processItemsInside function in CrucibleBlockEntity.
If item can't be processed, it should remain in hopper.
2. If hopper presents below crucible, all items, which were produced in reaction should be put inside that hopper. In case of hopper overflow, items should appear inside crucible with 0 momentum.

Symbol integration.
1.redstone signal should be able to turn metal symbols off. So, they won't cause any effect in presence of redstone signal.

Dispenser integration.
1. Dispenser should be able to drain powers from crucible, when quartz bottle is used. If there aren't enough power in crucible, operation will be cancelled.
If there aren't empty space in dispenser, bottle with essence will appear inside of cradle.

**Comment by hjake123** [comment]
I'm working on some of these features! Not all of them will function exactly as you described but it'll be close enough!

**Comment by hjake123** [comment]
Added in the next update.

**Comment by arsserpentarium** [comment]
thank you
