### ISSUE TITLE
Unable to enter dedicated server with this mod

### ISSUE THREAD

**Issue by Igno-miny** [hjake123/reactive#8]
As the title says. The server itself runs fine, but when a player attempts to enter a server with this mod they get kicked out. This does not cause a crash on either side.

Logs show the following lines on joining with my old modpack (which included the Connectivity mod):
`[17:34:11] [Netty Client IO #2/WARN] [co.co.Connectivity/]: io.netty.handler.codec.DecoderException: java.lang.NullPointerException:
Cannot invoke "net.minecraftforge.registries.ForgeRegistry.getValue(int)" because "registry" is null`
`[17:34:11] [Netty Client IO #2/WARN] [co.co.Connectivity/]: Packet not registered: ClientboundDisconnectPacket`
`[17:34:11] [Netty Client IO #2/WARN] [co.co.Connectivity/]: io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet`
`[17:34:11] [Netty Client IO #2/WARN] [co.co.Connectivity/]: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/1 (ClientboundAddExperienceOrbPacket) was larger than I expected, found 504528 bytes extra whilst reading packet 1`

This was replicated outside of the modpack, with only reactive and patchouli installed. However, the lines above do not show up without Connectivity installed, and it appears in the logs of both sides that it is a disconnect with no further information.

**Comment by hjake123** [comment]
Very interesting, thanks for the report

**Comment by hjake123** [comment]
The issue is resolved, but I found another multiplayer issue. In any case...
