### ISSUE TITLE
Displaced Block crashes server on load

### ISSUE THREAD

**Issue by Koolkubed** [hjake123/reactive#84]
**Version**
1.20.1-9.14.0 for forge

**What you expected**
I expected to be able to remove the first salt block I displaced without any issues.

**What actually happened**
the displaced block will not go away even when I remove the battery from under it.  trying to break it in creative and even trying to use /fill to get rid of it fail.  my server's console is constantly flooded with error reports, most notably
"[11:54:47] [Server thread/ERROR] [minecraft/LevelChunk]: A BlockEntity type dev.hyperlynx.reactive.be.DisplacedBlockEntity has thrown an exception trying to write state. It will not persist, Report this to the mod author", and players are having trouble joining the server now.

**Steps to reproduce**
1. place a motion salt block on a volt cell to cause it to become displaced
2. leave it that way as you shut down the server for the night
3. come back after turning the server back on and try to undo the displacement.

UPDATE: the block seems to be causing corruption, and now I can't join the server either.

**Comment by hjake123** [comment]
Ah! Yikes, ok, I'll try to figure this out right now. It should have returned to normal after removing the volt cell, or vanished with a single error message if the block information was broken somehow...

**Comment by hjake123** [comment]
In particular, I'm curious if there are any instances of 
`Something went wrong restoring block from displaced block. Report this to hyperlynx!`

**Comment by hjake123** [comment]
Whatever's going on, the block definitely should not be able to corrupt anything. What does your log say when you're disconnected?

**Comment by hjake123** [comment]
Found the issue! Your server is not corrupt most likely -- I'm just not handling displaced blocks that have lost their data correctly. I'll fix that and put out a patch that should resolve things.

**Comment by hjake123** [comment]
This fix will release as `9.14.1`
